name: Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: write
  issues: write
  pull-requests: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      run: npm run build
      
    - name: Test CLI functionality
      run: |
        npx tsx src/cli/cli.ts --version
        npx tsx src/cli/cli.ts --help
        
    - name: Generate changelog
      run: |
        echo "# Changelog" > CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "## [$(git describe --tags --abbrev=0)] - $(date +'%Y-%m-%d')" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "### Changes" >> CHANGELOG.md
        git log --oneline --since="$(git describe --tags --abbrev=0 HEAD~1)" --pretty=format:"- %s" >> CHANGELOG.md || echo "- Initial release" >> CHANGELOG.md
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          README.md
          GETTING_STARTED.md
          LICENSE
          content-examples/**
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}